name: Publish to test PyPI
on:
  - workflow_dispatch
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: python3 -m pip install --upgrade build && python3 -m build
    - name: Publish package to test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
